using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Nodes;
using Aog.Core.Machines.Axle;

namespace Aog.UI.Avalonia.ViewModels;

/// <summary>
/// View-model that assists operators in composing axle-centric kinematic profiles.
/// </summary>
public sealed class KinematicsProfileEditorViewModel : ObservableObject
{
    private readonly Func<DateTimeOffset> _clock;
    private readonly DelegateCommand _addJointCommand;
    private readonly DelegateCommand _addAxleCommand;
    private readonly DelegateCommand _addModeCommand;

    private IReadOnlyList<AxleIngestionMessage> _validationMessages;
    private string _profileId;
    private string _schemaVersion;
    private string _compatibilityMinimumCoreVersion;
    private string _compatibilitySchemaVersion;
    private string _exportedJson = string.Empty;

    /// <summary>
    /// Initializes a new instance of the <see cref="KinematicsProfileEditorViewModel"/> class.
    /// </summary>
    public KinematicsProfileEditorViewModel(Func<DateTimeOffset>? clock = null)
    {
        _clock = clock ?? (() => DateTimeOffset.UtcNow);
        _profileId = "profile.default";
        _schemaVersion = AxleCentricProfileLoader.SupportedSchemaVersion;
    _compatibilityMinimumCoreVersion = "1.2";
        _compatibilitySchemaVersion = AxleCentricProfileLoader.SupportedSchemaVersion;
        _validationMessages = Array.Empty<AxleIngestionMessage>();

        LateMeasurementPolicy = new LateMeasurementPolicyViewModel();
        Axles = new ObservableCollection<KinematicsAxleViewModel>();
        Joints = new ObservableCollection<KinematicsJointViewModel>();
        Modes = new ObservableCollection<KinematicsModeViewModel>();

        _addAxleCommand = new DelegateCommand(_ => AddAxleInternal());
        _addJointCommand = new DelegateCommand(_ => AddSequentialJoint(), _ => Axles.Count >= 2);
        _addModeCommand = new DelegateCommand(_ => AddModeInternal());

        AddAxleCommand = _addAxleCommand;
        AddJointCommand = _addJointCommand;
        AddModeCommand = _addModeCommand;

        Axles.CollectionChanged += OnAxlesChanged;
    }

    /// <summary>
    /// Gets or sets the profile identifier.
    /// </summary>
    public string ProfileId
    {
        get => _profileId;
        set => SetProperty(ref _profileId, value);
    }

    /// <summary>
    /// Gets or sets the schema version.
    /// </summary>
    public string SchemaVersion
    {
        get => _schemaVersion;
        set => SetProperty(ref _schemaVersion, value);
    }

    /// <summary>
    /// Gets or sets the minimum core version declared in the compatibility guard.
    /// </summary>
    public string CompatibilityMinimumCoreVersion
    {
        get => _compatibilityMinimumCoreVersion;
        set => SetProperty(ref _compatibilityMinimumCoreVersion, value);
    }

    /// <summary>
    /// Gets or sets the schema version captured in the compatibility guard.
    /// </summary>
    public string CompatibilitySchemaVersion
    {
        get => _compatibilitySchemaVersion;
        set => SetProperty(ref _compatibilitySchemaVersion, value);
    }

    /// <summary>
    /// Gets the late measurement policy being composed.
    /// </summary>
    public LateMeasurementPolicyViewModel LateMeasurementPolicy { get; }

    /// <summary>
    /// Gets the collection of axle nodes.
    /// </summary>
    public ObservableCollection<KinematicsAxleViewModel> Axles { get; }

    /// <summary>
    /// Gets the collection of joints linking axle nodes.
    /// </summary>
    public ObservableCollection<KinematicsJointViewModel> Joints { get; }

    /// <summary>
    /// Gets the operating modes declared in the profile.
    /// </summary>
    public ObservableCollection<KinematicsModeViewModel> Modes { get; }

    /// <summary>
    /// Gets the JSON exported during the last build operation.
    /// </summary>
    public string ExportedJson
    {
        get => _exportedJson;
        private set => SetProperty(ref _exportedJson, value);
    }

    /// <summary>
    /// Gets the validation messages generated by the last build.
    /// </summary>
    public IReadOnlyList<AxleIngestionMessage> ValidationMessages
    {
        get => _validationMessages;
        private set
        {
            if (!ReferenceEquals(_validationMessages, value))
            {
                _validationMessages = value;
                OnPropertyChanged();
                OnPropertyChanged(nameof(HasValidationErrors));
            }
        }
    }

    /// <summary>
    /// Gets a value indicating whether the last build produced validation errors.
    /// </summary>
    public bool HasValidationErrors => ValidationMessages.Any(m => m.Severity == AxleIngestionSeverity.Error);

    /// <summary>
    /// Gets the command that appends a new axle node.
    /// </summary>
    public DelegateCommand AddAxleCommand { get; }

    /// <summary>
    /// Gets the command that creates a sequential joint between the last two axles.
    /// </summary>
    public DelegateCommand AddJointCommand { get; }

    /// <summary>
    /// Gets the command that appends a new mode entry.
    /// </summary>
    public DelegateCommand AddModeCommand { get; }

    /// <summary>
    /// Builds the profile payload and validates it using the ingestion pipeline.
    /// </summary>
    public KinematicsProfileEditorResult BuildProfile()
    {
        var payload = ComposePayload();
        var options = new JsonSerializerOptions { WriteIndented = true };
        var json = payload.ToJsonString(options);

        var loader = new AxleCentricProfileLoader();
        var result = loader.Load(json);

        ValidationMessages = result.Messages;
        ExportedJson = json;
        return new KinematicsProfileEditorResult(json, result);
    }

    /// <summary>
    /// Creates a sample editor populated with representative data.
    /// </summary>
    public static KinematicsProfileEditorViewModel CreateSample()
    {
        var viewModel = new KinematicsProfileEditorViewModel(() => new DateTimeOffset(2025, 1, 1, 12, 0, 0, TimeSpan.Zero))
        {
            ProfileId = "rigs.sample.axle",
            SchemaVersion = AxleCentricProfileLoader.SupportedSchemaVersion,
            CompatibilityMinimumCoreVersion = "1.2",
            CompatibilitySchemaVersion = AxleCentricProfileLoader.SupportedSchemaVersion,
        };

        viewModel.Axles.Add(new KinematicsAxleViewModel("tractor.drive", AxleNodeRole.Drive, curvatureLimit: 0.35, slipLimit: 0.05));
        viewModel.Axles.Add(new KinematicsAxleViewModel("tractor.steer", AxleNodeRole.Steer, curvatureLimit: 0.4, slipLimit: 0.08));
        viewModel.Axles.Add(new KinematicsAxleViewModel("implement.toolbar", AxleNodeRole.Implement, curvatureLimit: null, slipLimit: 0.12));

        viewModel.Joints.Add(new KinematicsJointViewModel("tractor.drive", "tractor.steer", AxleJointType.Articulated));
        viewModel.Joints.Add(new KinematicsJointViewModel("tractor.steer", "implement.toolbar", AxleJointType.Rigid));

        viewModel.Modes.Add(new KinematicsModeViewModel("field", curvatureLimit: 0.4, slipLimit: 0.1, DriveDirectionPolicy.Bidirectional));
        viewModel.Modes.Add(new KinematicsModeViewModel("road", curvatureLimit: 0.15, slipLimit: 0.05, DriveDirectionPolicy.ForwardOnly));

        viewModel.LateMeasurementPolicy.AllowLateMeasurements = true;
        viewModel.LateMeasurementPolicy.MaximumLatencyMilliseconds = 250;

        return viewModel;
    }

    private void OnAxlesChanged(object? sender, NotifyCollectionChangedEventArgs e)
    {
        _addJointCommand.RaiseCanExecuteChanged();
    }

    private void AddAxleInternal()
    {
        var nextIndex = Axles.Count + 1;
        var identifier = $"axle.{nextIndex}";
        while (Axles.Any(axle => string.Equals(axle.Id, identifier, StringComparison.OrdinalIgnoreCase)))
        {
            nextIndex++;
            identifier = $"axle.{nextIndex}";
        }

        var role = Axles.Count == 0 ? AxleNodeRole.Drive : AxleNodeRole.Implement;
        var axle = new KinematicsAxleViewModel(identifier, role, curvatureLimit: null, slipLimit: null);
        Axles.Add(axle);

        if (Axles.Count >= 2)
        {
            var parent = Axles[^2];
            var child = Axles[^1];
            if (!Joints.Any(j => string.Equals(j.ParentId, parent.Id, StringComparison.OrdinalIgnoreCase)
                && string.Equals(j.ChildId, child.Id, StringComparison.OrdinalIgnoreCase)))
            {
                Joints.Add(new KinematicsJointViewModel(parent.Id, child.Id, AxleJointType.Rigid));
            }
        }
    }

    private void AddSequentialJoint()
    {
        if (Axles.Count < 2)
        {
            return;
        }

        var parent = Axles[^2];
        var child = Axles[^1];
        if (!Joints.Any(j => string.Equals(j.ParentId, parent.Id, StringComparison.OrdinalIgnoreCase)
            && string.Equals(j.ChildId, child.Id, StringComparison.OrdinalIgnoreCase)))
        {
            Joints.Add(new KinematicsJointViewModel(parent.Id, child.Id, AxleJointType.Rigid));
        }
    }

    private void AddModeInternal()
    {
        var identifier = $"mode-{Modes.Count + 1}";
        while (Modes.Any(mode => string.Equals(mode.Id, identifier, StringComparison.OrdinalIgnoreCase)))
        {
            identifier = $"mode-{Guid.NewGuid():N}";
        }

        Modes.Add(new KinematicsModeViewModel(identifier, curvatureLimit: 0.25, slipLimit: 0.05, DriveDirectionPolicy.Bidirectional));
    }

    private JsonObject ComposePayload()
    {
        var root = new JsonObject
        {
            ["schemaVersion"] = SchemaVersion,
            ["profileId"] = ProfileId,
            ["generatedAt"] = _clock().ToString("O"),
            ["compatibility"] = new JsonObject
            {
                ["minimumCoreVersion"] = CompatibilityMinimumCoreVersion,
                ["schemaVersion"] = CompatibilitySchemaVersion,
            },
        };

        var axles = new JsonArray();
        foreach (var axle in Axles)
        {
            var axleObject = new JsonObject
            {
                ["id"] = axle.Id,
                ["role"] = axle.Role.ToString(),
            };

            if (axle.CurvatureLimit.HasValue)
            {
                axleObject["curvatureLimit"] = axle.CurvatureLimit.Value;
            }

            if (axle.SlipLimit.HasValue)
            {
                axleObject["slipLimit"] = axle.SlipLimit.Value;
            }

            axles.Add(axleObject);
        }

        root["axles"] = axles;

        var joints = new JsonArray();
        foreach (var joint in Joints)
        {
            joints.Add(new JsonObject
            {
                ["parent"] = joint.ParentId,
                ["child"] = joint.ChildId,
                ["type"] = joint.Type.ToString(),
            });
        }

        root["joints"] = joints;

        var modes = new JsonObject();
        foreach (var mode in Modes)
        {
            modes[mode.Id] = new JsonObject
            {
                ["curvatureLimit"] = mode.CurvatureLimit,
                ["slipLimit"] = mode.SlipLimit,
                ["driveDirectionPolicy"] = mode.DriveDirectionPolicy.ToString(),
            };
        }

        root["modes"] = modes;

        root["lateMeasurementPolicy"] = new JsonObject
        {
            ["allowLateMeasurements"] = LateMeasurementPolicy.AllowLateMeasurements,
            ["maximumLatencyMilliseconds"] = LateMeasurementPolicy.MaximumLatencyMilliseconds,
        };

        return root;
    }
}

/// <summary>
/// Represents the result of exporting a kinematic profile.
/// </summary>
/// <param name="Json">The exported JSON payload.</param>
/// <param name="IngestionResult">Detailed ingestion outcome.</param>
public sealed record KinematicsProfileEditorResult(string Json, AxleIngestionResult IngestionResult);

/// <summary>
/// Presentation model for an axle entry.
/// </summary>
public sealed class KinematicsAxleViewModel : ObservableObject
{
    private string _id;
    private AxleNodeRole _role;
    private double? _curvatureLimit;
    private double? _slipLimit;

    public KinematicsAxleViewModel(string id, AxleNodeRole role, double? curvatureLimit, double? slipLimit)
    {
        if (string.IsNullOrWhiteSpace(id))
        {
            throw new ArgumentException("Axle identifier is required.", nameof(id));
        }

        _id = id;
        _role = role;
        _curvatureLimit = curvatureLimit;
        _slipLimit = slipLimit;
    }

    public string Id
    {
        get => _id;
        set => SetProperty(ref _id, value);
    }

    public AxleNodeRole Role
    {
        get => _role;
        set => SetProperty(ref _role, value);
    }

    public double? CurvatureLimit
    {
        get => _curvatureLimit;
        set => SetProperty(ref _curvatureLimit, value);
    }

    public double? SlipLimit
    {
        get => _slipLimit;
        set => SetProperty(ref _slipLimit, value);
    }
}

/// <summary>
/// Presentation model for a joint entry.
/// </summary>
public sealed class KinematicsJointViewModel : ObservableObject
{
    private string _parentId;
    private string _childId;
    private AxleJointType _type;

    public KinematicsJointViewModel(string parentId, string childId, AxleJointType type)
    {
        if (string.IsNullOrWhiteSpace(parentId))
        {
            throw new ArgumentException("Parent axle identifier is required.", nameof(parentId));
        }

        if (string.IsNullOrWhiteSpace(childId))
        {
            throw new ArgumentException("Child axle identifier is required.", nameof(childId));
        }

        _parentId = parentId;
        _childId = childId;
        _type = type;
    }

    public string ParentId
    {
        get => _parentId;
        set => SetProperty(ref _parentId, value);
    }

    public string ChildId
    {
        get => _childId;
        set => SetProperty(ref _childId, value);
    }

    public AxleJointType Type
    {
        get => _type;
        set => SetProperty(ref _type, value);
    }
}

/// <summary>
/// Presentation model for a mode entry.
/// </summary>
public sealed class KinematicsModeViewModel : ObservableObject
{
    private string _id;
    private double _curvatureLimit;
    private double _slipLimit;
    private DriveDirectionPolicy _driveDirectionPolicy;

    public KinematicsModeViewModel(string id, double curvatureLimit, double slipLimit, DriveDirectionPolicy driveDirectionPolicy)
    {
        if (string.IsNullOrWhiteSpace(id))
        {
            throw new ArgumentException("Mode identifier is required.", nameof(id));
        }

        _id = id;
        _curvatureLimit = curvatureLimit;
        _slipLimit = slipLimit;
        _driveDirectionPolicy = driveDirectionPolicy;
    }

    public string Id
    {
        get => _id;
        set => SetProperty(ref _id, value);
    }

    public double CurvatureLimit
    {
        get => _curvatureLimit;
        set => SetProperty(ref _curvatureLimit, value);
    }

    public double SlipLimit
    {
        get => _slipLimit;
        set => SetProperty(ref _slipLimit, value);
    }

    public DriveDirectionPolicy DriveDirectionPolicy
    {
        get => _driveDirectionPolicy;
        set => SetProperty(ref _driveDirectionPolicy, value);
    }
}

/// <summary>
/// Presentation model for the late measurement policy block.
/// </summary>
public sealed class LateMeasurementPolicyViewModel : ObservableObject
{
    private bool _allowLateMeasurements;
    private double _maximumLatencyMilliseconds;

    public bool AllowLateMeasurements
    {
        get => _allowLateMeasurements;
        set => SetProperty(ref _allowLateMeasurements, value);
    }

    public double MaximumLatencyMilliseconds
    {
        get => _maximumLatencyMilliseconds;
        set => SetProperty(ref _maximumLatencyMilliseconds, value);
    }
}
