<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Aog.Tools.PluginCompliance</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Aog.Plugins/Aog.Plugins.csproj" />
    <ProjectReference Include="../../src/Aog.Agio/Aog.Agio.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Aog.Tools.PluginCompliance.Tests" />
  </ItemGroup>
</Project>
