using System;
using System.Collections.Generic;

namespace Aog.Plugins.AutoSteer;

/// <summary>
/// Implements a standalone pure pursuit steering controller with deterministic preview state.
/// </summary>
public sealed class PurePursuitController
{
    private double _lookAheadDistance;

    public PurePursuitController(double lookAheadDistanceMeters = 5.0)
    {
        LookAheadDistance = lookAheadDistanceMeters;
    }

    /// <summary>
    /// Gets or sets the static look-ahead distance used by the controller (metres).
    /// </summary>
    public double LookAheadDistance
    {
        get => _lookAheadDistance;
        set
        {
            if (value <= 0)
            {
                throw new ArgumentOutOfRangeException(nameof(value), value, "Look-ahead distance must be positive.");
            }

            _lookAheadDistance = value;
        }
    }

    /// <summary>
    /// Gets or sets the steering angle limit applied to the controller output (radians).
    /// </summary>
    public double SteeringAngleLimitRadians { get; set; } = Math.PI / 180d * 35;

    /// <summary>
    /// Gets the last computed preview metrics.
    /// </summary>
    public PurePursuitPreview LastPreview { get; private set; } = PurePursuitPreview.Zero;

    /// <summary>
    /// Computes the steering angle required to follow the supplied path.
    /// </summary>
    public double ComputeSteeringAngle(VehicleState state, IReadOnlyList<PathPoint> path)
    {
        ArgumentNullException.ThrowIfNull(path);
        if (path.Count < 2)
        {
            throw new InvalidOperationException("Pure pursuit requires at least two path points.");
        }

        var closest = AutoSteerPathGeometry.FindClosestPoint(state, path);
        var crossTrack = AutoSteerPathGeometry.ComputeCrossTrack(state, closest);
        var target = AutoSteerPathGeometry.ComputeLookAheadTarget(path, closest, LookAheadDistance);

        var toTargetX = target.X - state.X;
        var toTargetY = target.Y - state.Y;
        var distanceToTarget = Math.Sqrt(toTargetX * toTargetX + toTargetY * toTargetY);
        if (distanceToTarget < 1e-9)
        {
            LastPreview = new PurePursuitPreview(
                crossTrack,
                headingErrorRadians: 0,
                LookAheadDistance,
                state.X,
                state.Y,
                state.HeadingRadians,
                controllerOutput: 0,
                targetCurvaturePerMeter: 0);
            return 0;
        }

        var headingToTarget = Math.Atan2(toTargetY, toTargetX);
        var headingError = AutoSteerMath.NormalizeAngle(headingToTarget - state.HeadingRadians);
        var curvature = 2 * Math.Sin(headingError) / Math.Max(distanceToTarget, 1e-6);
        var steering = AutoSteerPathGeometry.ComputePurePursuitSteering(state, toTargetX, toTargetY, distanceToTarget);

        LastPreview = new PurePursuitPreview(
            crossTrack,
            headingError,
            LookAheadDistance,
            target.X,
            target.Y,
            headingToTarget,
            controllerOutput: steering,
            targetCurvaturePerMeter: curvature);

        return Math.Clamp(steering, -SteeringAngleLimitRadians, SteeringAngleLimitRadians);
    }
}

/// <summary>
/// Captures the preview metrics generated by the pure pursuit controller.
/// </summary>
public readonly record struct PurePursuitPreview(
    double CrossTrackError,
    double HeadingErrorRadians,
    double LookAheadDistanceMeters,
    double TargetX,
    double TargetY,
    double TargetHeading,
    double ControllerOutput,
    double TargetCurvaturePerMeter)
{
    public static PurePursuitPreview Zero { get; } = new(
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0);
}
