<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Aog.Tools.LegacyDataMigrator</RootNamespace>
    <AssemblyName>legacy-data-migrator</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Parquet.Net" Version="4.17.0" />
  </ItemGroup>
</Project>
