<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>Aog.UI.Avalonia</RootNamespace>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <UseWPF>false</UseWPF>
    <UseWindowsForms>false</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="**/*.axaml" />
    <Page Remove="**/*.axaml" />
    <AvaloniaXaml Remove="**/*.axaml" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="**/*.axaml" Exclude="$(BaseIntermediateOutputPath)**;$(BaseOutputPath)**" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources/*.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.0.6" />
    <PackageReference Include="Avalonia.Desktop" Version="11.0.6" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.0.6" Condition="'$(Configuration)' == 'Debug'" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="11.0.6" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.0.6" />
    <PackageReference Include="Avalonia.Skia" Version="11.0.6" />
    <PackageReference Include="SkiaSharp" Version="2.88.6" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Aog.Core/Aog.Core.csproj" />
    <ProjectReference Include="../Aog.Plugins/Aog.Plugins.csproj" />
  </ItemGroup>
</Project>
