using System;
using System.Collections.Generic;
using System.Linq;

namespace Aog.Core.Reporting;

/// <summary>
/// Describes a report template that orchestrates section renderers and export outputs.
/// Templates are immutable and validated on construction to ensure deterministic behaviour.
/// </summary>
public sealed record ReportTemplate
{
    /// <summary>
    /// Initialises a new instance of the <see cref="ReportTemplate"/> class.
    /// </summary>
    /// <param name="id">Stable identifier of the template.</param>
    /// <param name="name">Human readable name of the template.</param>
    /// <param name="version">Semantic version of the template manifest.</param>
    /// <param name="scope">Scope level that the template operates on.</param>
    /// <param name="sections">Ordered collection of sections that compose the report.</param>
    /// <param name="outputs">Declared output formats generated by the report.</param>
    /// <exception cref="ArgumentException">Thrown when the template definition is invalid.</exception>
    public ReportTemplate(
        string id,
        string name,
        string version,
        ReportScopeKind scope,
        IEnumerable<ReportTemplateSection> sections,
        IEnumerable<ReportTemplateOutput> outputs)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(id);
        ArgumentException.ThrowIfNullOrWhiteSpace(name);
        ArgumentException.ThrowIfNullOrWhiteSpace(version);

        Id = id;
        Name = name;
        Version = version;
        Scope = scope;

        Sections = (sections ?? throw new ArgumentNullException(nameof(sections)))
            .Select(s => s ?? throw new ArgumentException("Template sections cannot contain null entries.", nameof(sections)))
            .ToArray();
        if (Sections.Count == 0)
        {
            throw new ArgumentException("Report templates must declare at least one section.", nameof(sections));
        }

        if (Sections.Select(s => s.SectionId).Distinct(StringComparer.OrdinalIgnoreCase).Count() != Sections.Count)
        {
            throw new ArgumentException("Report templates cannot contain duplicate section identifiers.", nameof(sections));
        }

        Outputs = (outputs ?? throw new ArgumentNullException(nameof(outputs)))
            .Select(o => o ?? throw new ArgumentException("Template outputs cannot contain null entries.", nameof(outputs)))
            .ToArray();
        if (Outputs.Count == 0)
        {
            throw new ArgumentException("Report templates must declare at least one output format.", nameof(outputs));
        }

        if (Outputs.Select(o => o.Format).Distinct(StringComparer.OrdinalIgnoreCase).Count() != Outputs.Count)
        {
            throw new ArgumentException("Report templates cannot contain duplicate output formats.", nameof(outputs));
        }
    }

    /// <summary>
    /// Stable identifier of the template.
    /// </summary>
    public string Id { get; }

    /// <summary>
    /// Display name of the template.
    /// </summary>
    public string Name { get; }

    /// <summary>
    /// Manifest version of the template.
    /// </summary>
    public string Version { get; }

    /// <summary>
    /// Scope level that the template operates on.
    /// </summary>
    public ReportScopeKind Scope { get; }

    /// <summary>
    /// Ordered sections that compose the report.
    /// </summary>
    public IReadOnlyList<ReportTemplateSection> Sections { get; }

    /// <summary>
    /// Output definitions declared by the template.
    /// </summary>
    public IReadOnlyList<ReportTemplateOutput> Outputs { get; }
}

/// <summary>
/// Identifies the scope at which a report template operates.
/// </summary>
public enum ReportScopeKind
{
    /// <summary>
    /// The template operates at the farm/organisation scope.
    /// </summary>
    Farm,

    /// <summary>
    /// The template operates at the season scope.
    /// </summary>
    Season,

    /// <summary>
    /// The template operates at the job scope.
    /// </summary>
    Job,

    /// <summary>
    /// The template operates at the session scope.
    /// </summary>
    Session,
}

/// <summary>
/// Represents a template section invocation.
/// </summary>
public sealed record ReportTemplateSection
{
    /// <summary>
    /// Initialises a new instance of the <see cref="ReportTemplateSection"/> class.
    /// </summary>
    /// <param name="sectionId">Identifier of the section provider to invoke.</param>
    /// <param name="isOptional">Indicates whether the section is optional.</param>
    /// <param name="parameters">Additional parameters forwarded to the section renderer.</param>
    public ReportTemplateSection(
        string sectionId,
        bool isOptional = false,
        IReadOnlyDictionary<string, string>? parameters = null)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(sectionId);

        SectionId = sectionId;
        IsOptional = isOptional;
        Parameters = parameters is null
            ? new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            : new Dictionary<string, string>(parameters, StringComparer.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Identifier of the section provider to invoke.
    /// </summary>
    public string SectionId { get; }

    /// <summary>
    /// Indicates whether the section is optional.
    /// </summary>
    public bool IsOptional { get; }

    /// <summary>
    /// Additional parameters forwarded to the section renderer.
    /// </summary>
    public IReadOnlyDictionary<string, string> Parameters { get; }
}

/// <summary>
/// Declares a report output format produced by a template.
/// </summary>
public sealed record ReportTemplateOutput
{
    /// <summary>
    /// Initialises a new instance of the <see cref="ReportTemplateOutput"/> class.
    /// </summary>
    /// <param name="format">Unique identifier of the output format (for example, <c>pdf</c>).</param>
    /// <param name="description">Human readable description of the output.</param>
    /// <param name="parameters">Optional parameters forwarded to export renderers.</param>
    public ReportTemplateOutput(
        string format,
        string description,
        IReadOnlyDictionary<string, string>? parameters = null)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(format);
        ArgumentException.ThrowIfNullOrWhiteSpace(description);

        Format = format;
        Description = description;
        Parameters = parameters is null
            ? new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            : new Dictionary<string, string>(parameters, StringComparer.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Unique identifier of the output format (for example, <c>pdf</c>).
    /// </summary>
    public string Format { get; }

    /// <summary>
    /// Human readable description of the output.
    /// </summary>
    public string Description { get; }

    /// <summary>
    /// Optional parameters forwarded to export renderers.
    /// </summary>
    public IReadOnlyDictionary<string, string> Parameters { get; }
}

/// <summary>
/// Represents the scope information supplied when generating a report.
/// </summary>
public sealed record ReportScope
{
    /// <summary>
    /// Initialises a new instance of the <see cref="ReportScope"/> class.
    /// </summary>
    /// <param name="kind">Scope level addressed by the report.</param>
    /// <param name="identifier">Stable identifier for the entity within the scope.</param>
    /// <param name="properties">Additional properties describing the scope.</param>
    public ReportScope(ReportScopeKind kind, string identifier, IReadOnlyDictionary<string, string>? properties = null)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(identifier);

        Kind = kind;
        Identifier = identifier;
        Properties = properties is null
            ? new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            : new Dictionary<string, string>(properties, StringComparer.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Scope level addressed by the report.
    /// </summary>
    public ReportScopeKind Kind { get; }

    /// <summary>
    /// Stable identifier for the entity within the scope.
    /// </summary>
    public string Identifier { get; }

    /// <summary>
    /// Additional properties describing the scope (for example, farm identifiers or date ranges).
    /// </summary>
    public IReadOnlyDictionary<string, string> Properties { get; }
}

/// <summary>
/// Additional options that influence report generation.
/// </summary>
public sealed record ReportGenerationOptions
{
    /// <summary>
    /// Initialises a new instance of the <see cref="ReportGenerationOptions"/> class.
    /// </summary>
    /// <param name="parameters">Custom parameters forwarded to section renderers.</param>
    /// <param name="requestedOutputs">Specific outputs requested by the caller. When empty the template defaults are used.</param>
    public ReportGenerationOptions(
        IReadOnlyDictionary<string, string>? parameters = null,
        IReadOnlyCollection<string>? requestedOutputs = null)
    {
        Parameters = parameters is null
            ? new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            : new Dictionary<string, string>(parameters, StringComparer.OrdinalIgnoreCase);
        RequestedOutputs = requestedOutputs is null
            ? Array.Empty<string>()
            : requestedOutputs.Distinct(StringComparer.OrdinalIgnoreCase).ToArray();
    }

    /// <summary>
    /// Custom parameters forwarded to section renderers.
    /// </summary>
    public IReadOnlyDictionary<string, string> Parameters { get; }

    /// <summary>
    /// Specific outputs requested by the caller. When empty the template defaults are used.
    /// </summary>
    public IReadOnlyCollection<string> RequestedOutputs { get; }
}
