<Project>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(ContinuousIntegrationBuild)' == '' and '$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
    <ContractsArtifactsDir>$(MSBuildThisFileDirectory)../artifacts/nuget</ContractsArtifactsDir>
    <RestoreAdditionalProjectSources>$(RestoreAdditionalProjectSources);$(ContractsArtifactsDir)</RestoreAdditionalProjectSources>
    <AogAbstractionsBaseVersion>0.1.0</AogAbstractionsBaseVersion>
    <AogAbstractionsPackageVersion>0.1.*</AogAbstractionsPackageVersion>
    <NexusCliAbstractionsBaseVersion>0.1.0</NexusCliAbstractionsBaseVersion>
    <NexusCliAbstractionsPackageVersion>0.1.*</NexusCliAbstractionsPackageVersion>
  </PropertyGroup>
</Project>
