namespace Aog.Core.Routing;

/// <summary>
/// Represents the type of producer registered for a routed topic.
/// Higher numeric values indicate higher priority when no explicit
/// override is present.
/// </summary>
public enum SourceKind
{
    /// <summary>
    /// Synthetic data generated by the composite simulation system.
    /// </summary>
    Simulation = 0,

    /// <summary>
    /// Replay data sourced from recorded telemetry files.
    /// </summary>
    Replay = 1,

    /// <summary>
    /// Real hardware inputs connected through AGiO or other live sources.
    /// </summary>
    Hardware = 2,
}
