// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: pumpkinpi.proto

package pumpkinpipb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PumpkinPiService_SetSteerTarget_FullMethodName    = "/pumpkinpi.v1.PumpkinPiService/SetSteerTarget"
	PumpkinPiService_StreamSteerStatus_FullMethodName = "/pumpkinpi.v1.PumpkinPiService/StreamSteerStatus"
	PumpkinPiService_ClaimAuthority_FullMethodName    = "/pumpkinpi.v1.PumpkinPiService/ClaimAuthority"
)

// PumpkinPiServiceClient is the client API for PumpkinPiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PumpkinPiServiceClient interface {
	SetSteerTarget(ctx context.Context, in *SetSteerTargetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	StreamSteerStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (PumpkinPiService_StreamSteerStatusClient, error)
	ClaimAuthority(ctx context.Context, in *AuthorityClaim, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type pumpkinPiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPumpkinPiServiceClient(cc grpc.ClientConnInterface) PumpkinPiServiceClient {
	return &pumpkinPiServiceClient{cc}
}

func (c *pumpkinPiServiceClient) SetSteerTarget(ctx context.Context, in *SetSteerTargetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PumpkinPiService_SetSteerTarget_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pumpkinPiServiceClient) StreamSteerStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (PumpkinPiService_StreamSteerStatusClient, error) {
	stream, err := c.cc.NewStream(ctx, &PumpkinPiService_ServiceDesc.Streams[0], PumpkinPiService_StreamSteerStatus_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &pumpkinPiServiceStreamSteerStatusClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PumpkinPiService_StreamSteerStatusClient interface {
	Recv() (*SteerStatus, error)
	grpc.ClientStream
}

type pumpkinPiServiceStreamSteerStatusClient struct {
	grpc.ClientStream
}

func (x *pumpkinPiServiceStreamSteerStatusClient) Recv() (*SteerStatus, error) {
	m := new(SteerStatus)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pumpkinPiServiceClient) ClaimAuthority(ctx context.Context, in *AuthorityClaim, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PumpkinPiService_ClaimAuthority_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PumpkinPiServiceServer is the server API for PumpkinPiService service.
// All implementations must embed UnimplementedPumpkinPiServiceServer
// for forward compatibility
type PumpkinPiServiceServer interface {
	SetSteerTarget(context.Context, *SetSteerTargetRequest) (*emptypb.Empty, error)
	StreamSteerStatus(*emptypb.Empty, PumpkinPiService_StreamSteerStatusServer) error
	ClaimAuthority(context.Context, *AuthorityClaim) (*emptypb.Empty, error)
	mustEmbedUnimplementedPumpkinPiServiceServer()
}

// UnimplementedPumpkinPiServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPumpkinPiServiceServer struct {
}

func (UnimplementedPumpkinPiServiceServer) SetSteerTarget(context.Context, *SetSteerTargetRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSteerTarget not implemented")
}
func (UnimplementedPumpkinPiServiceServer) StreamSteerStatus(*emptypb.Empty, PumpkinPiService_StreamSteerStatusServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamSteerStatus not implemented")
}
func (UnimplementedPumpkinPiServiceServer) ClaimAuthority(context.Context, *AuthorityClaim) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimAuthority not implemented")
}
func (UnimplementedPumpkinPiServiceServer) mustEmbedUnimplementedPumpkinPiServiceServer() {}

// UnsafePumpkinPiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PumpkinPiServiceServer will
// result in compilation errors.
type UnsafePumpkinPiServiceServer interface {
	mustEmbedUnimplementedPumpkinPiServiceServer()
}

func RegisterPumpkinPiServiceServer(s grpc.ServiceRegistrar, srv PumpkinPiServiceServer) {
	s.RegisterService(&PumpkinPiService_ServiceDesc, srv)
}

func _PumpkinPiService_SetSteerTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSteerTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PumpkinPiServiceServer).SetSteerTarget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PumpkinPiService_SetSteerTarget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PumpkinPiServiceServer).SetSteerTarget(ctx, req.(*SetSteerTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PumpkinPiService_StreamSteerStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PumpkinPiServiceServer).StreamSteerStatus(m, &pumpkinPiServiceStreamSteerStatusServer{stream})
}

type PumpkinPiService_StreamSteerStatusServer interface {
	Send(*SteerStatus) error
	grpc.ServerStream
}

type pumpkinPiServiceStreamSteerStatusServer struct {
	grpc.ServerStream
}

func (x *pumpkinPiServiceStreamSteerStatusServer) Send(m *SteerStatus) error {
	return x.ServerStream.SendMsg(m)
}

func _PumpkinPiService_ClaimAuthority_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorityClaim)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PumpkinPiServiceServer).ClaimAuthority(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PumpkinPiService_ClaimAuthority_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PumpkinPiServiceServer).ClaimAuthority(ctx, req.(*AuthorityClaim))
	}
	return interceptor(ctx, in, info, handler)
}

// PumpkinPiService_ServiceDesc is the grpc.ServiceDesc for PumpkinPiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PumpkinPiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pumpkinpi.v1.PumpkinPiService",
	HandlerType: (*PumpkinPiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetSteerTarget",
			Handler:    _PumpkinPiService_SetSteerTarget_Handler,
		},
		{
			MethodName: "ClaimAuthority",
			Handler:    _PumpkinPiService_ClaimAuthority_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSteerStatus",
			Handler:       _PumpkinPiService_StreamSteerStatus_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pumpkinpi.proto",
}
