<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Aog.Tools.LegacyJobMigrator</RootNamespace>
    <AssemblyName>legacy-job-migrator</AssemblyName>
  </PropertyGroup>
</Project>
